#!/usr/bin/node

// Example of a git-release-manifest.json file.
/*
{
	"repositories": {
		"brave/brave-browser": {
			"filenameSelector": "Bravearm64Universal[.]apk$"
		},
		"uazo/cromite": {
			"filenameSelector": "arm64_ChromePublic[.]apk$"
		},
		"T8RIN/ImageToolbox": {
			"filenameSelector": "image-toolbox-.*-foss-arm64-v8a[.]apk$"
		}
	}
}
*/

import { execSync } from "child_process";
import fs from "node:fs";

const boldgreen = "\x1b[1;32m";
const green = "\x1b[32m";
const yellow = "\x1b[33m";
const reset = "\x1b[0m";

(async () => {
	const manifestFilePath = process.argv[2];
	if (!manifestFilePath) {
		console.error("no git-release-update-manifest.json file provided");
		console.log("usage: git-release-update <MANIFEST>");
		process.exit(1);
	}

	const manifest = JSON.parse(fs.readFileSync(manifestFilePath));

	const rxFilename = /[^/]+$/g;
	const rxFilenameSanitizer = /[/\\;*?'"<>]/g;
	const rxLatestVersion = /.*\/download\/([^/]+).*/g;
	const rxShellCommandSanitizer = /[;$`'"\\]/g;

	const getLatestDownloadUrl = async (repository, filenameSelector) => {
		return new Promise(async (resolve, reject) => {
			fetch(`https://api.github.com/repos/${repository}/releases`).then(res => {
				res.json().then(arr => {
					const assets = arr[0].assets;
					if (!assets || assets.length === 0)
						return reject("no assets found in API response.");
					try {
						const rxTargetFilename = new RegExp(filenameSelector);
						for (const asset of assets) {
							const downloadUrl = asset.browser_download_url;
							const filename = downloadUrl.match(rxFilename)[0];
							if (rxTargetFilename.test(filename))
								return resolve(downloadUrl);
						}
						reject("no version found");
					} catch(err) {
						reject(err);
					}
				}).catch(err => reject(err));
			}).catch(err => reject(err));
		});
	};

	const sleep = async ms => new Promise(resolve => setTimeout(resolve, ms));

	for (const repository of Object.keys(manifest.repositories)) {
		const repoData = manifest.repositories[repository];
		const filenameSelector = repoData.filenameSelector;
		const latestVersion = repoData.latestVersion;
		console.log(`   (${repository}) Last downloaded version: ${green}${latestVersion}${reset}`);
		await getLatestDownloadUrl(repository, filenameSelector).then(downloadUrl => {
			const version = downloadUrl.replace(rxLatestVersion, "$1");
			if (!version) {
				console.error("no version found in URL: " + downloadUrl);
				return;
			}
			console.log(`   (${repository}) Latest version: ${green}${version}${reset}`);
			if (version !== latestVersion) {
				const cleanRepo = repository.replaceAll(rxShellCommandSanitizer, "");
				const cleanVersion = version.replaceAll(rxShellCommandSanitizer, "");
				downloadUrl = downloadUrl.replaceAll(rxShellCommandSanitizer, "");
				console.log(` ${boldgreen}↓${reset} (${repository}) Requesting download...`);
				execSync(`termux-notification --action "xdg-open '${downloadUrl}'" -t 'Git Release Update' -c '${cleanRepo} released ${cleanVersion}'`);
				manifest.repositories[repository].latestVersion = version;
				fs.writeFileSync(manifestFilePath, JSON.stringify(manifest, null, "\t"));
			}
		}).catch(err => console.error(err));
		await sleep(2000);
	}

	console.log("");

	process.exit(0);
})();
