#!/bin/bash

if [[ -z $@ || $@ == "-h" || $@ == "--help" ]]; then
	echo -e "Resets and spoofs interface.\n  Usage: ifreset <interface>"
else
	phy="phy$(echo $@ | sed -e s/^[a-z]*//)"
	echo "Resetting & spoofing $@ ..."

	# reset
	iw dev $@ del &> /dev/null
	iw dev $@mon del &> /dev/null
	iw phy $phy interface add $@ type managed
	rfkill unblock wifi

	# spoof
	macchanger -rb $@ &> /dev/null
	ifconfig $@ up

	# check
	macchanger $@
fi
