#!/bin/bash

# Start subtracting X from Y until we reached Z
# Usage: finishsubtracting 1 10 0

current=0
increment=1
limit=false

if [ ! -z $1 ]; then
	increment=$1
fi

if [ ! -z $2 ]; then
	current=$2
fi

if [ ! -z $3 ]; then
	limit=$3
fi

if [ $increment -gt 0 ]; then
	while true; do
		[ $limit != false ] && [ $current -lt $limit ] && exit
		echo $current
		current=$(($current-$increment))
	done
else
	echo "error: increment may not be 0"
fi
