#!/bin/bash

# Start adding X to Y until we reached Z
# Usage: startadding 1 3 5

current=0
increment=1
limit=false

[ ! -z $1 ] && increment=$1
[ ! -z $2 ] && current=$2
[ ! -z $3 ] && limit=$3

if [ $increment -gt 0 ]; then
	while true; do
		[ $limit != false ] && [ $current -gt $limit ] && exit
		echo $current
		current=$(($current+$increment))
	done
else
	echo "error: increment may not be 0"
fi
