#!/bin/bash

show_help() {
	echo -e "Set given interface to given mode.\n  Usage: ifmode <interface> <mode>"
	exit
}

for cvar in $@; do
	if [[ $cvar == "-h" || $cvar == "-help" || $cvar == "--help" ]]; then
		show_help
	fi
done

if [[ -z $2 ]]; then
	show_help
else
	ifconfig $1 down
	iwconfig $1 mode $2
	ifconfig $1 up
fi
