#!/bin/bash

# this command should not be used on virtual interfaces

show_help() {
	echo -e "Resets and spoofs interface.\nThis command should not be used on virtual interfaces!\n  Usage: ifreset <interface>"
	exit
}

for cvar in $@; do
	if [[ $cvar == "-h" || $cvar == "-help" || $cvar == "--help" ]]; then
		show_help
	fi
done

if [[ -z $@ ]]; then
	show_help
else
	echo "Resetting & spoofing $@ ..."

	phy="phy$(echo $1 | sed -e s/^[a-z]*//)"

	# reset
	iw dev $1 del &> /dev/null
	iw dev $1mon del &> /dev/null
	iw phy $phy interface add $1 type managed

	# spoof
	ifconfig $1 down
	macchanger -rb $1 &> /dev/null
	ifconfig $1 up

	# check
	sleep 0.2
	macchanger $1
fi

# debug
