#!/usr/bin/node

// Utility to define JSON object property and value from a shell environment.

const fs = require("fs");

process.env.NO_COLOR = "1";

const propValue = process.argv[4];
if (!propValue) {
	console.error("no new object property value provided.");
	process.exit(1);
}

const propName = process.argv[3];
if (!propName) {
	console.error("no object property name provided.");
	process.exit(1);
}

const filePath = process.argv[2];
if (!filePath) {
	console.error("no JSON filepath provided.");
	process.exit(1);
}

try {
	const plaintext = fs.readFileSync(process.argv[2]);
	const json = JSON.parse(plaintext);
	json[propName] = propValue;
	fs.writeFileSync(filePath, JSON.stringify(json));
} catch (err) {
	console.error(err);
	process.exit(1);
}
