#!/usr/bin/node

// Utility to read JSON object properties from a shell environment.

const fs = require("fs");

const propName = process.argv[3];
if (!propName) {
	console.error("no object property name provided.");
	process.exit(1);
}

if (!process.argv[2]) {
	console.error("no JSON filepath provided.");
	process.exit(1);
}

try {
	const plaintext = fs.readFileSync(process.argv[2]);
	const json = JSON.parse(plaintext);
	if (!json.hasOwnProperty(propName)) {
		console.error(`object property with given name ${propName} not found.`);
		process.exit(1);
	}
	console.log(json[propName]);
} catch (err) {
	console.error(err);
	process.exit(1);
}
