#!/bin/bash

PROMPT=false

for VAR in $@; do
	if [[ \
		! -z $(echo $VAR | grep -a "^-") \
	&& \
		! -z $(echo $VAR | grep -ai "r\|recursive") \
	]]; then
		PROMPT=true
	fi
done

if $PROMPT; then
	echo -e "\e[1;31mWARNING\e[0m"
	read -p "Are you sure you want to rm recursively? y/N " ANSWER
	if [[ ! -z $(grep -ai "^y\$" <<< $ANSWER) ]]; then
		/bin/rm "$@"
	else
		echo Aborted.
	fi
else
	/bin/rm "$@"
fi
