#!/bin/bash

[ -z "$1" ] && echo "usage: sigquit <pattern>" && exit 1;

PIDS=(`ps aux | grep "$1" | grep -v "$0 $1" | grep -v "grep" | awk '{print $2}'`)
for PID in $PIDS; do
	echo "  Sending SIGQUIT to [$PID]"
	kill -3 "$PID"
done
