#!/bin/bash

# Start adding $1 to $2 every $3 (or 1) seconds until we reached $4
# Usage: startadding 1 3 1 5

interval=1
current=0
increment=1
limit=false

if [ ! -z $1 ]; then
	increment=$1
fi

if [ ! -z $2 ]; then
	current=$2
fi

if [ ! -z $3 ]; then
	interval=$3
fi

if [ ! -z $4 ]; then
	limit=$3
else
	echo "Usage: startadding <summand> <startsummand> <interval> <finalsum>"
	echo "Example: startadding 1 3 1 5"
	exit
fi

if [ $increment -gt 0 ]; then
	while true; do
		if [ $limit != false ] && [ $current -gt $limit ]; then
			exit
		fi
		echo $current
		current=$(($current+$increment))
		sleep $interval
	done
else
	echo "error: increment may not be 0"
fi
