#!/bin/bash

show_help() {
	echo -e "Connect to WPA/WPA2 wireless network.\n  Usage: wpaconnect <interface> <path to wpa_supplicant config>"
	exit
}

for cvar in $@; do
	if [[ $cvar == "-h" || $cvar == "-help" || $cvar == "--help" ]]; then
		show_help
	fi
done

if [[ -z $2 ]]; then
	show_help
else
	pids=$(ps aux | grep -a "wpa_supplicant .*[-]i builtin\( .*\|\$\)" | awk "{print \$2}")
	for pid in $pids; do
		kill -9 $pid &> /dev/null
	done
	dhclient -r "$1"

	ip link set "$1" down \
	&& ip link set "$1" up \
	&& sleep 1 \
	&& wpa_supplicant -i "$1" -c "$2" -D wext -B &> /dev/null

	sleep 2
	dhclient && echo "Connected."
fi
