#!/bin/bash

if [ -z "$1" ]; then
	dhclient -r &>/dev/null;
	sigterm "wpa_supplicant" &>/dev/null;
	sigterm "wpa_supplicant" &>/dev/null;
	sigkill dhclient &>/dev/null;
	echo "All interfaces disconnected.";
else
	dhclient -r "$1" &>/dev/null;
	sigterm "wpa_supplicant\\s\+\-i\\s\+$1" &>/dev/null;
	sigterm "wpa_supplicant\\s\+\-i\\s\+$1" &>/dev/null;
	sigkill "dhclient\\s\+\-v\\s\+$1" &>/dev/null;
	sigkill "dhclient\\s\+$1" &>/dev/null;
	down "$1" &>/dev/null;
	echo "$1 disconnected.";
fi;
